name: fr-zhykos-demo-opt-apps

services:

    user-api:
        build: ../UserAPI
        ports:
            - "9001:9001"

    product-api:
        build: ../ProductAPI
        ports:
            - "9002:9002"
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://localhost:9002/actuator/health || exit 1

    postgres-products:
        image: postgres:16.3-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        volumes:
            - ./postgres/init-products.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "9012:5432"
        depends_on:
            product-api:
                condition: service_healthy