_format_version: "3.0"
plugins:
- config:
    batch_flush_delay: null
    batch_span_count: null
    connect_timeout: 1000
    endpoint: http://opentelemetry-collector:4318
    header_type: preserve
    headers: {}
    http_response_header_for_traceid: null
    propagation:
      clear: null
      default_format: jaeger
      extract: null
      inject: null
    queue:
      initial_retry_delay: 0.01
      max_batch_size: 1
      max_bytes: null
      max_coalescing_delay: 1
      max_entries: 10000
      max_retry_delay: 60
      max_retry_time: 60
    read_timeout: 5000
    resource_attributes: {}
    sampling_rate: null
    send_timeout: 5000
  enabled: true
  name: opentelemetry
  protocols:
  - http
  - https
services:
- connect_timeout: 60000
  enabled: true
  host: 192.168.1.140
  name: users
  port: 9001
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: users
    path_handling: v0
    paths:
    - /users-api
    preserve_host: false
    protocols:
    - http
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
    tags:
    - user
    - users
    - shop
  tags:
  - user
  - ' users'
  - ' shop'
  write_timeout: 60000
