# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    target-branch: "develop"
    directory: "/UserAPI/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    target-branch: "develop"
    directory: "/ProductAPI/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    target-branch: "develop"
    directory: "/BenchmarkOpenTelemetryCollector/api/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    target-branch: "develop"
    directory: "/BenchmarkOpenTelemetryCollector/bench-locust/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    target-branch: "develop"
    directory: "/Infra/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    target-branch: "develop"
    directory: "/InvoiceAPI/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    target-branch: "develop"
    directory: "/OrderAPI/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/front-home/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    target-branch: "develop"
    directories:
      - "/BasketAPI-SpringBoot/"
      - "/front-home/"
      - "/Infra/"
      - "/InvoiceAPI/"
      - "/OrderAPI/"
      - "/ProductAPI/"
      - "ShopE2E/tests/resources/"
      - "/UserAPI/"
    schedule:
      interval: "weekly"
