# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/UserAPI/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/ProductAPI/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/BenchmarkOpenTelemetryCollector/api/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/BenchmarkOpenTelemetryCollector/bench-locust/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/Infra/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/InvoiceAPI/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/OrderAPI/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/front-home/"
    schedule:
      interval: "weekly"
