# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # https://github.com/Zhykos/cool-tools/issues/336
  # - package-ecosystem: "deno"
  #   target-branch: "develop"
  #   directories:
  #     - "/DenoEasyObservability/api/"
  #     - "/ErrorUseCase/todo-api/"
  #     - "/ErrorUseCase-2/api/"
  #   schedule:
  #     interval: "monthly"

  - package-ecosystem: "docker"
    target-branch: "develop"
    directories:
      - "/BasketAPI-SpringBoot/"
      - "/InvoiceAPI/"
      - "/OrderAPI/"
      - "/Presentations/observability/"
      - "/ProductAPI/"
      - "/Shop-front/"
      - "/UserAPI/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker-compose"
    target-branch: "develop"
    directories:
      - "/ErrorUseCase/"
      - "/Infra/"
      - "/Shop-E2E/tests/resources/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "gomod"
    target-branch: "develop"
    directory: "/OrderAPI/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "maven"
    target-branch: "develop"
    directories:
      - "/BasketAPI-SpringBoot/"
      - "/BenchmarkOpenTelemetryCollector/api/"
      - "/InvoiceAPI/"
      - "/ProductAPI/"
      - "/UserAPI/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    target-branch: "develop"
    directories:
      - "/DenoEasyObservability/e2e/"
      - "/ErrorUseCase/e2e/"
      - "/ErrorUseCase/front/"
      - "/ErrorUseCase-2/e2e/"
      - "/Presentations/observability/"
      - "/Shop-E2E/"
      - "/Shop-front/"
    schedule:
      interval: "monthly"
