@startuml Arch

archimate #Application "Users\n(SpringBoot)" as UsersJava <<application-service>>

archimate #Technology "Users\n(H2)" as UsersDB <<technology-service>>

UsersJava --> UsersDB

@enduml