name: fr-zhykos-demo-opt-all

include:
  - path: Infra/docker-compose.yml

services:

  user-api:
    build: UserAPI
    ports:
      - "9001:9001"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9001/actuator/health || exit 1

  product-api:
    build: ProductAPI
    ports:
      - "9002:9002"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318
      - SPRING_R2DBC_URL=r2dbc:postgresql://${EXTERNAL_IP}:9012/db
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9002/actuator/health || exit 1

  basket-api:
    build: ./BasketAPI/target/docker/stage
    ports:
      - "9003:9000"
    environment:
      - OTEL_SERVICE_NAME=fr.zhykos.demo.otp/BasketAPI
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318
      - JAVA_OPTS=-DOTEL_SERVICE_NAME=basket -DOTEL_TRACES_EXPORTER=otlp -DOTEL_METRICS_EXPORTER=otlp -DOTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4317 -Xms512m -Xmx2048m -javaagent:/opt/docker/opentelemetry-javaagent/opentelemetry-javaagent-1.11.0.jar -server

  order-api:
    build: OrderAPI
    ports:
      - "9004:9004"
    environment:
      - MONGODB_URI=mongodb://root:password@${EXTERNAL_IP}:9014
      - USER_API_URI=http://user-api:9001
      - PRODUCT_API_URI=http://product-api:9002
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318
      - KAFKA_URI=kafka:9092

  invoice-api:
    build: InvoiceAPI
    ports:
      - "9005:9005"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318
      - KAFKA_URI=kafka:9092