service:
  pipelines:
    metrics:
      receivers: [prometheus/user]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [logging, loki]