spring:
  application:
    name: UserAPI
  profiles:
    active: json-logging
  datasource:
    url: jdbc:h2:mem:users
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 9001

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
      http:
        server:
          requests: true