# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deno Easy Observability E2E

on:
  push:
    branches:
      - develop
      - main
      - feature/**
      - hotfix/**
      - release/**
    paths:
      - 'DenoEasyObservability/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'DenoEasyObservability/**'

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Launch API
      working-directory: ./DenoEasyObservability/api
      run: |
        docker build -t deno_easy_observability .
        docker run -d -p 8000:8000 deno_easy_observability

    - name: Create and launch the Playwright tests
      working-directory: ./DenoEasyObservability/e2e
      run: |
        npm install
        npx playwright install firefox --with-deps
        npm run test
    
    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: playwright-report
        path: ./DenoEasyObservability/e2e/playwright-report/
        retention-days: 30
    
    - name: Upload Playwright snapshots
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: playwright-snapshots
        path: ./DenoEasyObservability/e2e/tests/resources/snapshots
        retention-days: 30

    - name: Dump docker logs
      if: ${{ failure() }}
      uses: jwalton/gh-docker-logs@v2
