# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Presentation E2E

on:
  push:
    branches:
      - develop
      - main
      - feature/**
      - hotfix/**
      - release/**
      - dependabot/**
  pull_request:
    branches:
      - develop

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Launch Docker
      working-directory: ./doc/presentation
      run: |
        docker build -t presentation .
        docker run -d -p 3026:80 presentation

    - name: Create and launch the Playwright tests
      working-directory: ./doc/presentation
      run: |
        npm install
        npx playwright install firefox --with-deps
        npm run test
    
    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: playwright-report
        path: ./doc/presentation/playwright-report/
        retention-days: 30
    
    - name: Upload Playwright snapshots
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: playwright-snapshots
        path: ./doc/presentation/tests/resources/snapshots
        retention-days: 30

    - name: Dump docker logs
      if: ${{ failure() }}
      uses: jwalton/gh-docker-logs@v2
