# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Shop E2E

on:
  push:
    branches:
      - develop
      - main
      - feature/**
      - hotfix/**
      - release/**
    paths:
      - '**'
      - '!DenoEasyObservability/**'
      - '!ErrorUseCase/**'
      - '!ErrorUseCase-2/**'
      - '!Presentations/**'
  pull_request:
    branches:
      - develop
    paths:
      - '**'
      - '!DenoEasyObservability/**'
      - '!ErrorUseCase/**'
      - '!ErrorUseCase-2/**'
      - '!Presentations/**'

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Replace IP address in all files
      run: |
        current_ip=$(hostname -I | awk '{print $1}')
        echo "Current IP address: $current_ip"
        find . -type f -exec sed -i "s/<<MY_IP_ADDRESS>>/$current_ip/g" {} +

    - name: Launch Docker Compose for infrastructure
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./Shop-E2E/tests/resources/docker-compose.yml"

    - name: Create and launch the Playwright tests
      working-directory: ./Shop-E2E
      run: |
        npm install
        npx playwright install firefox --with-deps
        npm run test
    
    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: playwright-report
        path: ./Shop-E2E/playwright-report/
        retention-days: 30
    
    - name: Upload Playwright snapshots
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: playwright-snapshots
        path: ./Shop-E2E/tests/resources/snapshots
        retention-days: 30

    - name: Dump docker logs
      if: ${{ failure() }}
      uses: jwalton/gh-docker-logs@v2
